# .github/workflows/update.yml
name: Update aggregated VLESS list

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:      # ручной запуск

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip

      - name: Run aggregator
        run: python update_aggregated.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto update aggregated VLESS list"
          commit_message: "Auto update VLESS configs"
          file_pattern: aggregated.txt aggregated_base64.txt best_ru_de.txt best_ru_de_base64.txt
